<?php

// autoload_namespaces.php @generated by Composer

$vendorDir = dirname(dirname(__FILE__));
$baseDir = dirname($vendorDir);

return array(
    'fpdf' => array($vendorDir . '/itbz/fpdf/src'),
    'Xethron\\MigrationsGenerator' => array($vendorDir . '/xethron/migrations-generator/src'),
    'Webpatser\\Uuid' => array($vendorDir . '/webpatser/laravel-uuid/src'),
    'Way\\Generators' => array($vendorDir . '/way/generators/src', $vendorDir . '/xethron/laravel-4-generators/src'),
    'System' => array($vendorDir . '/phpseclib/phpseclib/phpseclib'),
    'Sorskod\\Larasponse' => array($vendorDir . '/sorskod/larasponse/src'),
    'Sabberworm\\CSS' => array($vendorDir . '/sabberworm/php-css-parser/lib'),
    'Prophecy\\' => array($vendorDir . '/phpspec/prophecy/src'),
    'PhpSpec' => array($vendorDir . '/phpspec/phpspec/src'),
    'PHPExcel' => array($vendorDir . '/phpoffice/phpexcel/Classes'),
    'Net' => array($vendorDir . '/phpseclib/phpseclib/phpseclib'),
    'Namshi\\JOSE' => array($vendorDir . '/namshi/jose/src'),
    'Mockery' => array($vendorDir . '/mockery/mockery/library'),
    'Math' => array($vendorDir . '/phpseclib/phpseclib/phpseclib'),
    'Maatwebsite\\Excel\\' => array($vendorDir . '/maatwebsite/excel/src'),
    'Jenssegers\\Mongodb' => array($vendorDir . '/jenssegers/mongodb/src'),
    'Jenssegers\\Eloquent' => array($vendorDir . '/jenssegers/mongodb/src'),
    'JakubOnderka\\PhpConsoleHighlighter' => array($vendorDir . '/jakub-onderka/php-console-highlighter/src'),
    'JakubOnderka\\PhpConsoleColor' => array($vendorDir . '/jakub-onderka/php-console-color/src'),
    'File' => array($vendorDir . '/phpseclib/phpseclib/phpseclib'),
    'Doctrine\\DBAL\\' => array($vendorDir . '/doctrine/dbal/lib'),
    'Doctrine\\Common\\Lexer\\' => array($vendorDir . '/doctrine/lexer/lib'),
    'Doctrine\\Common\\Inflector\\' => array($vendorDir . '/doctrine/inflector/lib'),
    'Doctrine\\Common\\Collections\\' => array($vendorDir . '/doctrine/collections/lib'),
    'Diff' => array($vendorDir . '/phpspec/php-diff/lib'),
    'Crypt' => array($vendorDir . '/phpseclib/phpseclib/phpseclib'),
    'Asm89\\Stack' => array($vendorDir . '/asm89/stack-cors/src'),
);
